package com.SunuBtrust360_Enrol.wsdl;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2023-12-01T16:54:21.256Z
 * Generated source version: 4.0.3
 *
 */
@WebService(targetNamespace = "http://adminws.signserver.org/", name = "AdminWS")
@XmlSeeAlso({ObjectFactory.class})
public interface AdminWS {

    @WebMethod
    @RequestWrapper(localName = "getStatus", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.GetStatus")
    @ResponseWrapper(localName = "getStatusResponse", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.GetStatusResponse")
    @WebResult(name = "return", targetNamespace = "")
    public WsWorkerStatus getStatus(

        @WebParam(name = "workerId", targetNamespace = "")
        int workerId
    ) throws InvalidWorkerIdException_Exception, AdminNotAuthorizedException_Exception;

    @WebMethod
    @RequestWrapper(localName = "queryArchiveWithIds", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.QueryArchiveWithIds")
    @ResponseWrapper(localName = "queryArchiveWithIdsResponse", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.QueryArchiveWithIdsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ArchiveEntry> queryArchiveWithIds(

        @WebParam(name = "uniqueIds", targetNamespace = "")
        java.util.List<String> uniqueIds,
        @WebParam(name = "includeData", targetNamespace = "")
        boolean includeData
    ) throws SignServerException_Exception, AdminNotAuthorizedException_Exception;

    @WebMethod
    @RequestWrapper(localName = "removeWorkerProperty", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.RemoveWorkerProperty")
    @ResponseWrapper(localName = "removeWorkerPropertyResponse", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.RemoveWorkerPropertyResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean removeWorkerProperty(

        @WebParam(name = "workerId", targetNamespace = "")
        int workerId,
        @WebParam(name = "key", targetNamespace = "")
        String key
    ) throws AdminNotAuthorizedException_Exception;

    @WebMethod
    @RequestWrapper(localName = "addAuthorizedClient", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.AddAuthorizedClient")
    @ResponseWrapper(localName = "addAuthorizedClientResponse", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.AddAuthorizedClientResponse")
    public void addAuthorizedClient(

        @WebParam(name = "workerId", targetNamespace = "")
        int workerId,
        @WebParam(name = "authClient", targetNamespace = "")
        AuthorizedClient authClient
    ) throws AdminNotAuthorizedException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getWorkers", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.GetWorkers")
    @ResponseWrapper(localName = "getWorkersResponse", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.GetWorkersResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<Integer> getWorkers(

        @WebParam(name = "workerType", targetNamespace = "")
        int workerType
    ) throws AdminNotAuthorizedException_Exception;

    @WebMethod
    @RequestWrapper(localName = "queryAuditLog", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.QueryAuditLog")
    @ResponseWrapper(localName = "queryAuditLogResponse", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.QueryAuditLogResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<LogEntry> queryAuditLog(

        @WebParam(name = "startIndex", targetNamespace = "")
        int startIndex,
        @WebParam(name = "max", targetNamespace = "")
        int max,
        @WebParam(name = "condition", targetNamespace = "")
        java.util.List<QueryCondition> condition,
        @WebParam(name = "ordering", targetNamespace = "")
        java.util.List<QueryOrdering> ordering
    ) throws SignServerException_Exception, AdminNotAuthorizedException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getSigningValidityNotBefore", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.GetSigningValidityNotBefore")
    @ResponseWrapper(localName = "getSigningValidityNotBeforeResponse", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.GetSigningValidityNotBeforeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public javax.xml.datatype.XMLGregorianCalendar getSigningValidityNotBefore(

        @WebParam(name = "workerId", targetNamespace = "")
        int workerId
    ) throws AdminNotAuthorizedException_Exception, CryptoTokenOfflineException_Exception;

    @WebMethod
    @RequestWrapper(localName = "importCertificateChain", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.ImportCertificateChain")
    @ResponseWrapper(localName = "importCertificateChainResponse", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.ImportCertificateChainResponse")
    public void importCertificateChain(

        @WebParam(name = "workerId", targetNamespace = "")
        int workerId,
        @WebParam(name = "certificateChain", targetNamespace = "")
        java.util.List<byte[]> certificateChain,
        @WebParam(name = "alias", targetNamespace = "")
        String alias,
        @WebParam(name = "authenticationCode", targetNamespace = "")
        String authenticationCode
    ) throws OperationUnsupportedException_Exception, AdminNotAuthorizedException_Exception, CryptoTokenOfflineException_Exception, CertificateException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getSigningValidityNotAfter", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.GetSigningValidityNotAfter")
    @ResponseWrapper(localName = "getSigningValidityNotAfterResponse", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.GetSigningValidityNotAfterResponse")
    @WebResult(name = "return", targetNamespace = "")
    public javax.xml.datatype.XMLGregorianCalendar getSigningValidityNotAfter(

        @WebParam(name = "workerId", targetNamespace = "")
        int workerId
    ) throws AdminNotAuthorizedException_Exception, CryptoTokenOfflineException_Exception;

    @WebMethod
    @RequestWrapper(localName = "destroyKey", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.DestroyKey")
    @ResponseWrapper(localName = "destroyKeyResponse", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.DestroyKeyResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean destroyKey(

        @WebParam(name = "signerId", targetNamespace = "")
        int signerId,
        @WebParam(name = "purpose", targetNamespace = "")
        int purpose
    ) throws InvalidWorkerIdException_Exception, AdminNotAuthorizedException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getAuthorizedClients", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.GetAuthorizedClients")
    @ResponseWrapper(localName = "getAuthorizedClientsResponse", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.GetAuthorizedClientsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<AuthorizedClient> getAuthorizedClients(

        @WebParam(name = "workerId", targetNamespace = "")
        int workerId
    ) throws AdminNotAuthorizedException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getPKCS10CertificateRequestForAlias2", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.GetPKCS10CertificateRequestForAlias2")
    @ResponseWrapper(localName = "getPKCS10CertificateRequestForAlias2Response", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.GetPKCS10CertificateRequestForAlias2Response")
    @WebResult(name = "return", targetNamespace = "")
    public CertReqData getPKCS10CertificateRequestForAlias2(

        @WebParam(name = "signerId", targetNamespace = "")
        int signerId,
        @WebParam(name = "certReqInfo", targetNamespace = "")
        Pkcs10CertReqInfo certReqInfo,
        @WebParam(name = "explicitEccParameters", targetNamespace = "")
        boolean explicitEccParameters,
        @WebParam(name = "keyAlias", targetNamespace = "")
        String keyAlias
    ) throws InvalidWorkerIdException_Exception, AdminNotAuthorizedException_Exception, CryptoTokenOfflineException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getSignerCertificateChain", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.GetSignerCertificateChain")
    @ResponseWrapper(localName = "getSignerCertificateChainResponse", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.GetSignerCertificateChainResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<byte[]> getSignerCertificateChain(

        @WebParam(name = "signerId", targetNamespace = "")
        int signerId
    ) throws AdminNotAuthorizedException_Exception, CryptoTokenOfflineException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getPKCS10CertificateRequestForAlias", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.GetPKCS10CertificateRequestForAlias")
    @ResponseWrapper(localName = "getPKCS10CertificateRequestForAliasResponse", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.GetPKCS10CertificateRequestForAliasResponse")
    @WebResult(name = "return", targetNamespace = "")
    public Base64SignerCertReqData getPKCS10CertificateRequestForAlias(

        @WebParam(name = "signerId", targetNamespace = "")
        int signerId,
        @WebParam(name = "certReqInfo", targetNamespace = "")
        Pkcs10CertReqInfo certReqInfo,
        @WebParam(name = "explicitEccParameters", targetNamespace = "")
        boolean explicitEccParameters,
        @WebParam(name = "keyAlias", targetNamespace = "")
        String keyAlias
    ) throws InvalidWorkerIdException_Exception, AdminNotAuthorizedException_Exception, CryptoTokenOfflineException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getPKCS10CertificateRequestForKey", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.GetPKCS10CertificateRequestForKey")
    @ResponseWrapper(localName = "getPKCS10CertificateRequestForKeyResponse", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.GetPKCS10CertificateRequestForKeyResponse")
    @WebResult(name = "return", targetNamespace = "")
    public Base64SignerCertReqData getPKCS10CertificateRequestForKey(

        @WebParam(name = "signerId", targetNamespace = "")
        int signerId,
        @WebParam(name = "certReqInfo", targetNamespace = "")
        Pkcs10CertReqInfo certReqInfo,
        @WebParam(name = "explicitEccParameters", targetNamespace = "")
        boolean explicitEccParameters,
        @WebParam(name = "defaultKey", targetNamespace = "")
        boolean defaultKey
    ) throws InvalidWorkerIdException_Exception, AdminNotAuthorizedException_Exception, CryptoTokenOfflineException_Exception;

    @WebMethod
    @RequestWrapper(localName = "testKey", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.TestKey")
    @ResponseWrapper(localName = "testKeyResponse", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.TestKeyResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<KeyTestResult> testKey(

        @WebParam(name = "signerId", targetNamespace = "")
        int signerId,
        @WebParam(name = "alias", targetNamespace = "")
        String alias,
        @WebParam(name = "authCode", targetNamespace = "")
        String authCode
    ) throws InvalidWorkerIdException_Exception, AdminNotAuthorizedException_Exception, CryptoTokenOfflineException_Exception, KeyStoreException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getWorkerId", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.GetWorkerId")
    @ResponseWrapper(localName = "getWorkerIdResponse", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.GetWorkerIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int getWorkerId(

        @WebParam(name = "workerName", targetNamespace = "")
        String workerName
    ) throws AdminNotAuthorizedException_Exception;

    @WebMethod
    @RequestWrapper(localName = "queryTokenEntries", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.QueryTokenEntries")
    @ResponseWrapper(localName = "queryTokenEntriesResponse", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.QueryTokenEntriesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public TokenSearchResults queryTokenEntries(

        @WebParam(name = "workerId", targetNamespace = "")
        int workerId,
        @WebParam(name = "startIndex", targetNamespace = "")
        int startIndex,
        @WebParam(name = "max", targetNamespace = "")
        int max,
        @WebParam(name = "condition", targetNamespace = "")
        java.util.List<QueryCondition> condition,
        @WebParam(name = "ordering", targetNamespace = "")
        java.util.List<QueryOrdering> ordering,
        @WebParam(name = "includeData", targetNamespace = "")
        boolean includeData
    ) throws OperationUnsupportedException_Exception, AdminNotAuthorizedException_Exception, InvalidWorkerIdException_Exception, SignServerException_Exception, AuthorizationDeniedException_Exception, CryptoTokenOfflineException_Exception, QueryException_Exception;

    @WebMethod
    @RequestWrapper(localName = "removeKey", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.RemoveKey")
    @ResponseWrapper(localName = "removeKeyResponse", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.RemoveKeyResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean removeKey(

        @WebParam(name = "signerId", targetNamespace = "")
        int signerId,
        @WebParam(name = "alias", targetNamespace = "")
        String alias
    ) throws InvalidWorkerIdException_Exception, SignServerException_Exception, AdminNotAuthorizedException_Exception, CryptoTokenOfflineException_Exception, KeyStoreException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getSignerCertificate", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.GetSignerCertificate")
    @ResponseWrapper(localName = "getSignerCertificateResponse", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.GetSignerCertificateResponse")
    @WebResult(name = "return", targetNamespace = "")
    public byte[] getSignerCertificate(

        @WebParam(name = "signerId", targetNamespace = "")
        int signerId
    ) throws AdminNotAuthorizedException_Exception, CryptoTokenOfflineException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getGlobalConfiguration", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.GetGlobalConfiguration")
    @ResponseWrapper(localName = "getGlobalConfigurationResponse", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.GetGlobalConfigurationResponse")
    @WebResult(name = "return", targetNamespace = "")
    public WsGlobalConfiguration getGlobalConfiguration()
 throws AdminNotAuthorizedException_Exception;

    @WebMethod
    @RequestWrapper(localName = "uploadSignerCertificateChain", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.UploadSignerCertificateChain")
    @ResponseWrapper(localName = "uploadSignerCertificateChainResponse", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.UploadSignerCertificateChainResponse")
    public void uploadSignerCertificateChain(

        @WebParam(name = "signerId", targetNamespace = "")
        int signerId,
        @WebParam(name = "signerCerts", targetNamespace = "")
        java.util.List<byte[]> signerCerts,
        @WebParam(name = "scope", targetNamespace = "")
        String scope
    ) throws IllegalRequestException_Exception, AdminNotAuthorizedException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getCurrentWorkerConfig", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.GetCurrentWorkerConfig")
    @ResponseWrapper(localName = "getCurrentWorkerConfigResponse", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.GetCurrentWorkerConfigResponse")
    @WebResult(name = "return", targetNamespace = "")
    public WsWorkerConfig getCurrentWorkerConfig(

        @WebParam(name = "workerId", targetNamespace = "")
        int workerId
    ) throws AdminNotAuthorizedException_Exception;

    @WebMethod
    @RequestWrapper(localName = "removeGlobalProperty", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.RemoveGlobalProperty")
    @ResponseWrapper(localName = "removeGlobalPropertyResponse", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.RemoveGlobalPropertyResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean removeGlobalProperty(

        @WebParam(name = "scope", targetNamespace = "")
        String scope,
        @WebParam(name = "key", targetNamespace = "")
        String key
    ) throws AdminNotAuthorizedException_Exception;

    @WebMethod
    @RequestWrapper(localName = "queryArchive", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.QueryArchive")
    @ResponseWrapper(localName = "queryArchiveResponse", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.QueryArchiveResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ArchiveEntry> queryArchive(

        @WebParam(name = "startIndex", targetNamespace = "")
        int startIndex,
        @WebParam(name = "max", targetNamespace = "")
        int max,
        @WebParam(name = "condition", targetNamespace = "")
        java.util.List<QueryCondition> condition,
        @WebParam(name = "ordering", targetNamespace = "")
        java.util.List<QueryOrdering> ordering,
        @WebParam(name = "includeData", targetNamespace = "")
        boolean includeData
    ) throws SignServerException_Exception, AdminNotAuthorizedException_Exception;

    @WebMethod
    @RequestWrapper(localName = "setGlobalProperty", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.SetGlobalProperty")
    @ResponseWrapper(localName = "setGlobalPropertyResponse", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.SetGlobalPropertyResponse")
    public void setGlobalProperty(

        @WebParam(name = "scope", targetNamespace = "")
        String scope,
        @WebParam(name = "key", targetNamespace = "")
        String key,
        @WebParam(name = "value", targetNamespace = "")
        String value
    ) throws AdminNotAuthorizedException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getKeyUsageCounterValue", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.GetKeyUsageCounterValue")
    @ResponseWrapper(localName = "getKeyUsageCounterValueResponse", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.GetKeyUsageCounterValueResponse")
    @WebResult(name = "return", targetNamespace = "")
    public long getKeyUsageCounterValue(

        @WebParam(name = "workerId", targetNamespace = "")
        int workerId
    ) throws AdminNotAuthorizedException_Exception, CryptoTokenOfflineException_Exception;

    @WebMethod
    @RequestWrapper(localName = "process", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.Process")
    @ResponseWrapper(localName = "processResponse", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.ProcessResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<byte[]> process(

        @WebParam(name = "workerIdOrName", targetNamespace = "")
        String workerIdOrName,
        @WebParam(name = "processRequest", targetNamespace = "")
        java.util.List<byte[]> processRequest
    ) throws IllegalRequestException_Exception, InvalidWorkerIdException_Exception, SignServerException_Exception, AdminNotAuthorizedException_Exception, CryptoTokenOfflineException_Exception;

    @WebMethod
    @RequestWrapper(localName = "globalReload", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.GlobalReload")
    @ResponseWrapper(localName = "globalReloadResponse", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.GlobalReloadResponse")
    public void globalReload()
 throws AdminNotAuthorizedException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getPKCS10CertificateRequestForKey2", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.GetPKCS10CertificateRequestForKey2")
    @ResponseWrapper(localName = "getPKCS10CertificateRequestForKey2Response", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.GetPKCS10CertificateRequestForKey2Response")
    @WebResult(name = "return", targetNamespace = "")
    public CertReqData getPKCS10CertificateRequestForKey2(

        @WebParam(name = "signerId", targetNamespace = "")
        int signerId,
        @WebParam(name = "certReqInfo", targetNamespace = "")
        Pkcs10CertReqInfo certReqInfo,
        @WebParam(name = "explicitEccParameters", targetNamespace = "")
        boolean explicitEccParameters,
        @WebParam(name = "defaultKey", targetNamespace = "")
        boolean defaultKey
    ) throws InvalidWorkerIdException_Exception, AdminNotAuthorizedException_Exception, CryptoTokenOfflineException_Exception;

    @WebMethod
    @RequestWrapper(localName = "activateSigner", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.ActivateSigner")
    @ResponseWrapper(localName = "activateSignerResponse", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.ActivateSignerResponse")
    public void activateSigner(

        @WebParam(name = "signerId", targetNamespace = "")
        int signerId,
        @WebParam(name = "authenticationCode", targetNamespace = "")
        String authenticationCode
    ) throws InvalidWorkerIdException_Exception, CryptoTokenAuthenticationFailureException_Exception, AdminNotAuthorizedException_Exception, CryptoTokenOfflineException_Exception;

    @WebMethod
    @RequestWrapper(localName = "removeAuthorizedClient", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.RemoveAuthorizedClient")
    @ResponseWrapper(localName = "removeAuthorizedClientResponse", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.RemoveAuthorizedClientResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean removeAuthorizedClient(

        @WebParam(name = "workerId", targetNamespace = "")
        int workerId,
        @WebParam(name = "authClient", targetNamespace = "")
        AuthorizedClient authClient
    ) throws AdminNotAuthorizedException_Exception;

    @WebMethod
    @RequestWrapper(localName = "globalResync", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.GlobalResync")
    @ResponseWrapper(localName = "globalResyncResponse", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.GlobalResyncResponse")
    public void globalResync()
 throws ResyncException_Exception, AdminNotAuthorizedException_Exception;

    @WebMethod
    @RequestWrapper(localName = "generateSignerKey", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.GenerateSignerKey")
    @ResponseWrapper(localName = "generateSignerKeyResponse", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.GenerateSignerKeyResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String generateSignerKey(

        @WebParam(name = "signerId", targetNamespace = "")
        int signerId,
        @WebParam(name = "keyAlgorithm", targetNamespace = "")
        String keyAlgorithm,
        @WebParam(name = "keySpec", targetNamespace = "")
        String keySpec,
        @WebParam(name = "alias", targetNamespace = "")
        String alias,
        @WebParam(name = "authCode", targetNamespace = "")
        String authCode
    ) throws InvalidWorkerIdException_Exception, AdminNotAuthorizedException_Exception, CryptoTokenOfflineException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getPKCS10CertificateRequest", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.GetPKCS10CertificateRequest")
    @ResponseWrapper(localName = "getPKCS10CertificateRequestResponse", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.GetPKCS10CertificateRequestResponse")
    @WebResult(name = "return", targetNamespace = "")
    public Base64SignerCertReqData getPKCS10CertificateRequest(

        @WebParam(name = "signerId", targetNamespace = "")
        int signerId,
        @WebParam(name = "certReqInfo", targetNamespace = "")
        Pkcs10CertReqInfo certReqInfo,
        @WebParam(name = "explicitEccParameters", targetNamespace = "")
        boolean explicitEccParameters
    ) throws InvalidWorkerIdException_Exception, AdminNotAuthorizedException_Exception, CryptoTokenOfflineException_Exception;

    @WebMethod
    @RequestWrapper(localName = "setWorkerProperty", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.SetWorkerProperty")
    @ResponseWrapper(localName = "setWorkerPropertyResponse", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.SetWorkerPropertyResponse")
    public void setWorkerProperty(

        @WebParam(name = "workerId", targetNamespace = "")
        int workerId,
        @WebParam(name = "key", targetNamespace = "")
        String key,
        @WebParam(name = "value", targetNamespace = "")
        String value
    ) throws AdminNotAuthorizedException_Exception;

    @WebMethod
    @RequestWrapper(localName = "uploadSignerCertificate", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.UploadSignerCertificate")
    @ResponseWrapper(localName = "uploadSignerCertificateResponse", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.UploadSignerCertificateResponse")
    public void uploadSignerCertificate(

        @WebParam(name = "signerId", targetNamespace = "")
        int signerId,
        @WebParam(name = "signerCert", targetNamespace = "")
        byte[] signerCert,
        @WebParam(name = "scope", targetNamespace = "")
        String scope
    ) throws IllegalRequestException_Exception, AdminNotAuthorizedException_Exception;

    @WebMethod
    @RequestWrapper(localName = "deactivateSigner", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.DeactivateSigner")
    @ResponseWrapper(localName = "deactivateSignerResponse", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.DeactivateSignerResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean deactivateSigner(

        @WebParam(name = "signerId", targetNamespace = "")
        int signerId
    ) throws InvalidWorkerIdException_Exception, AdminNotAuthorizedException_Exception, CryptoTokenOfflineException_Exception;

    @WebMethod
    @RequestWrapper(localName = "reloadConfiguration", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.ReloadConfiguration")
    @ResponseWrapper(localName = "reloadConfigurationResponse", targetNamespace = "http://adminws.signserver.org/", className = "com.SunuBtrust360_Enrol.wsdl.ReloadConfigurationResponse")
    public void reloadConfiguration(

        @WebParam(name = "workerId", targetNamespace = "")
        int workerId
    ) throws AdminNotAuthorizedException_Exception;
}
