
package com.SunuBtrust360_Enrol.wsdl;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.3
 * 2023-12-01T16:54:21.216Z
 * Generated source version: 4.0.3
 */

@WebFault(name = "AdminNotAuthorizedException", targetNamespace = "http://adminws.signserver.org/")
public class AdminNotAuthorizedException_Exception extends Exception {

    private AdminNotAuthorizedException faultInfo;

    public AdminNotAuthorizedException_Exception() {
        super();
    }

    public AdminNotAuthorizedException_Exception(String message) {
        super(message);
    }

    public AdminNotAuthorizedException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public AdminNotAuthorizedException_Exception(String message, AdminNotAuthorizedException adminNotAuthorizedException) {
        super(message);
        this.faultInfo = adminNotAuthorizedException;
    }

    public AdminNotAuthorizedException_Exception(String message, AdminNotAuthorizedException adminNotAuthorizedException, Throwable cause) {
        super(message, cause);
        this.faultInfo = adminNotAuthorizedException;
    }

    public AdminNotAuthorizedException getFaultInfo() {
        return this.faultInfo;
    }
}
