
package com.SunuBtrust360_Enrol.wsdl;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.3
 * 2023-12-01T16:54:21.239Z
 * Generated source version: 4.0.3
 */

@WebFault(name = "AuthorizationDeniedException", targetNamespace = "http://adminws.signserver.org/")
public class AuthorizationDeniedException_Exception extends Exception {

    private AuthorizationDeniedException faultInfo;

    public AuthorizationDeniedException_Exception() {
        super();
    }

    public AuthorizationDeniedException_Exception(String message) {
        super(message);
    }

    public AuthorizationDeniedException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public AuthorizationDeniedException_Exception(String message, AuthorizationDeniedException authorizationDeniedException) {
        super(message);
        this.faultInfo = authorizationDeniedException;
    }

    public AuthorizationDeniedException_Exception(String message, AuthorizationDeniedException authorizationDeniedException, Throwable cause) {
        super(message, cause);
        this.faultInfo = authorizationDeniedException;
    }

    public AuthorizationDeniedException getFaultInfo() {
        return this.faultInfo;
    }
}
