
package com.SunuBtrust360_Enrol.wsdl;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.3
 * 2023-12-01T16:54:21.250Z
 * Generated source version: 4.0.3
 */

@WebFault(name = "CryptoTokenAuthenticationFailureException", targetNamespace = "http://adminws.signserver.org/")
public class CryptoTokenAuthenticationFailureException_Exception extends Exception {

    private CryptoTokenAuthenticationFailureException faultInfo;

    public CryptoTokenAuthenticationFailureException_Exception() {
        super();
    }

    public CryptoTokenAuthenticationFailureException_Exception(String message) {
        super(message);
    }

    public CryptoTokenAuthenticationFailureException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public CryptoTokenAuthenticationFailureException_Exception(String message, CryptoTokenAuthenticationFailureException cryptoTokenAuthenticationFailureException) {
        super(message);
        this.faultInfo = cryptoTokenAuthenticationFailureException;
    }

    public CryptoTokenAuthenticationFailureException_Exception(String message, CryptoTokenAuthenticationFailureException cryptoTokenAuthenticationFailureException, Throwable cause) {
        super(message, cause);
        this.faultInfo = cryptoTokenAuthenticationFailureException;
    }

    public CryptoTokenAuthenticationFailureException getFaultInfo() {
        return this.faultInfo;
    }
}
