
package com.SunuBtrust360_Enrol.wsdl;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.3
 * 2023-12-01T16:54:21.224Z
 * Generated source version: 4.0.3
 */

@WebFault(name = "CryptoTokenOfflineException", targetNamespace = "http://adminws.signserver.org/")
public class CryptoTokenOfflineException_Exception extends Exception {

    private CryptoTokenOfflineException faultInfo;

    public CryptoTokenOfflineException_Exception() {
        super();
    }

    public CryptoTokenOfflineException_Exception(String message) {
        super(message);
    }

    public CryptoTokenOfflineException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public CryptoTokenOfflineException_Exception(String message, CryptoTokenOfflineException cryptoTokenOfflineException) {
        super(message);
        this.faultInfo = cryptoTokenOfflineException;
    }

    public CryptoTokenOfflineException_Exception(String message, CryptoTokenOfflineException cryptoTokenOfflineException, Throwable cause) {
        super(message, cause);
        this.faultInfo = cryptoTokenOfflineException;
    }

    public CryptoTokenOfflineException getFaultInfo() {
        return this.faultInfo;
    }
}
