
package com.SunuBtrust360_Enrol.wsdl;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.3
 * 2023-12-01T16:54:21.247Z
 * Generated source version: 4.0.3
 */

@WebFault(name = "IllegalRequestException", targetNamespace = "http://adminws.signserver.org/")
public class IllegalRequestException_Exception extends Exception {

    private IllegalRequestException faultInfo;

    public IllegalRequestException_Exception() {
        super();
    }

    public IllegalRequestException_Exception(String message) {
        super(message);
    }

    public IllegalRequestException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public IllegalRequestException_Exception(String message, IllegalRequestException illegalRequestException) {
        super(message);
        this.faultInfo = illegalRequestException;
    }

    public IllegalRequestException_Exception(String message, IllegalRequestException illegalRequestException, Throwable cause) {
        super(message, cause);
        this.faultInfo = illegalRequestException;
    }

    public IllegalRequestException getFaultInfo() {
        return this.faultInfo;
    }
}
