
package com.SunuBtrust360_Enrol.wsdl;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.3
 * 2023-12-01T16:54:21.235Z
 * Generated source version: 4.0.3
 */

@WebFault(name = "KeyStoreException", targetNamespace = "http://adminws.signserver.org/")
public class KeyStoreException_Exception extends Exception {

    private KeyStoreException faultInfo;

    public KeyStoreException_Exception() {
        super();
    }

    public KeyStoreException_Exception(String message) {
        super(message);
    }

    public KeyStoreException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public KeyStoreException_Exception(String message, KeyStoreException keyStoreException) {
        super(message);
        this.faultInfo = keyStoreException;
    }

    public KeyStoreException_Exception(String message, KeyStoreException keyStoreException, Throwable cause) {
        super(message, cause);
        this.faultInfo = keyStoreException;
    }

    public KeyStoreException getFaultInfo() {
        return this.faultInfo;
    }
}
