
package com.SunuBtrust360_Enrol.wsdl;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.3
 * 2023-12-01T16:54:21.253Z
 * Generated source version: 4.0.3
 */

@WebFault(name = "ResyncException", targetNamespace = "http://adminws.signserver.org/")
public class ResyncException_Exception extends Exception {

    private ResyncException faultInfo;

    public ResyncException_Exception() {
        super();
    }

    public ResyncException_Exception(String message) {
        super(message);
    }

    public ResyncException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ResyncException_Exception(String message, ResyncException resyncException) {
        super(message);
        this.faultInfo = resyncException;
    }

    public ResyncException_Exception(String message, ResyncException resyncException, Throwable cause) {
        super(message, cause);
        this.faultInfo = resyncException;
    }

    public ResyncException getFaultInfo() {
        return this.faultInfo;
    }
}
