
package com.SunuBtrust360_Enrol.wsdl;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.3
 * 2023-12-01T16:54:21.221Z
 * Generated source version: 4.0.3
 */

@WebFault(name = "SignServerException", targetNamespace = "http://adminws.signserver.org/")
public class SignServerException_Exception extends Exception {

    private SignServerException faultInfo;

    public SignServerException_Exception() {
        super();
    }

    public SignServerException_Exception(String message) {
        super(message);
    }

    public SignServerException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public SignServerException_Exception(String message, SignServerException signServerException) {
        super(message);
        this.faultInfo = signServerException;
    }

    public SignServerException_Exception(String message, SignServerException signServerException, Throwable cause) {
        super(message, cause);
        this.faultInfo = signServerException;
    }

    public SignServerException getFaultInfo() {
        return this.faultInfo;
    }
}
